name: CI Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Change to your desired version (e.g., '3.8', '3.9')

      - name: Create virtual environment
        run: python3 -m venv myenv

      - name: Install dependencies
        run: |
          source myenv/bin/activate
          pip install -r requirements.txt  # Replace with your dependency installation command

      - name: Run tests
        run: |
          source myenv/bin/activate
          pytest  # Replace with your test or build command
