name: CI with CyberGhost VPN

on:
  push:
    branches:
      - main

jobs:
steps:
  - name: Install dependencies
    run: |
      apk add --no-cache nodejs npm git
  - name: Checkout code
    uses: actions/checkout@v3
  - name: Install project dependencies
    run: |
      npm install
  - name: Run tests
    run: |
      npm test
  vpn-job:
    runs-on: ubuntu-latest
    container:
      image: qmcgaw/gluetun
      options: --cap-add=NET_ADMIN --device /dev/net/tun
    env:
      VPN_SERVICE_PROVIDER: cyberghost
      OPENVPN_USER: ${{ secrets.CYBERGHOST_USER }}
      OPENVPN_PASSWORD: ${{ secrets.CYBERGHOST_PASSWORD }}
      SERVER_COUNTRIES: Netherlands  # Change to your desired country
    steps:
      - name: Install dependencies
        run: |
          apk add --no-cache python3 py3-pip git
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install test dependencies
        run: |
          pip3 install pytest
      - name: Run tests
        run: |
          pytest
